version: "3.8"

services:
  db:
    image: postgres:13
    container_name: breizhsport-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./backend
    container_name: breizhsport-api
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  test:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    container_name: breizhsport_test
    depends_on:
      - api

volumes:
  pgdata:
